parserOptions:
  ecmaVersion: latest
  overrides:
    - files: [gramex/apps/admin2/schedule.js]
      parserOptions:
        sourceType: module
env:
  browser: true
  es6: true
# These default plugins are installed in the root gramex director via package.json
plugins: ["html", "template"]
# Styles are based on recommended eslint fields, but with specific overrides
extends: "eslint:recommended"
ignorePatterns:
  # Ignore generated documentation scripts
  - mkdocs/*
  # Ignore generated files for test caes
  - tests/filemanager/tape.js
  # Ignore test cases that are intended to fail
  - pytest/complexity_basic/*
