# This file has contain secrets you can use in gramex.yaml.
# DO NOT COMMIT THIS FILE. .gitignore ignores this file by default.
# Instead, add this file on your server manually or using CI tools.

# When you add keys like this...

# GOOGLE_AUTH_KEY: ...
# GOOGLE_AUTH_SECRET: ...
# TWITTER_KEY: ...
# TWITTER_SECRET: ...

# ... you can use them in gramex.yaml as $GOOGLE_AUTH_KEY, etc.
