# Pin miniconda3 version to the latest one that has Python 3.7 in the base env
FROM continuumio/miniconda3:4.8.2

LABEL description="{{ description }}"
LABEL version="{{ version }}"
LABEL maintainer="{{ author_email }}"

# Install system requirements. The ORDER of runs is critical. Keep them exactly in this order
RUN apt update && apt install -y pandoc
RUN pip install --upgrade pip orderedattrdict tornado
RUN conda install -c conda-forge -c gramener gramex -y
RUN apt -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
    libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
    libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 \
    libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
    libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
    fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

# Expose port 9988 by default. It can be overridden, e.g. via -p 3333:3333
EXPOSE 9988

# Use CMD instead of ENTRYPOINT. It can be overridden to run /bin/bash
CMD ["gramex"]
